const { DatabaseSync } = require('node:sqlite');
const db = new DatabaseSync('C:/Users/chugaa boe/Documents/Default Project/backend/data/stationery.db');

// Expected: [name, unit, price] exactly as uploaded by the user
const EXPECTED = [
 ['REAM A4 (A1 & NO1) PIECE', 'piece', 10000],
 ['REAM A4 (A1 & NO1) CARTON', 'carton', 50000],
 ['REAM A3 MAGNA PIECE', 'piece', 30000],
 ['REAM A3 MAGNA CARTON', 'carton', 150000],
 ['REAM A3 A1 PIECE', 'piece', 32000],
 ['REAM A3 A1 CARTON', 'carton', 160000],
 ['BINDING TAPE BLACK PIECE', 'piece', 3500],
 ['PENCIL NATARAJ PIECE', 'piece', 300],
 ['PENCIL NATARAJ DOZEN', 'dozen', 3000],
 ['PENCIL NATARAJ OUTER', 'outer', 30000],
 ['PENCIL CHINA PIECE', 'piece', 100],
 ['PENCIL CHINA DOZEN', 'dozen', 800],
 ['PENCIL DOMS DOZEN', 'dozen', 2500],
 ['PENCIL DOMS OUTER', 'outer', 25000],
 ['MANILA BLUE PIECE', 'piece', 6000],
 ['MANILA GREEN PIECE', 'piece', 6000],
 ['MANILA ORANGE PIECE', 'piece', 6000],
 ['TRANSPARENT BLUE PIECE', 'piece', 11000],
 ['TRANSPARENT WHITE PIECE', 'piece', 10000],
 ['PEN (BLUE/RED/BLACK) PIECE', 'piece', 200],
 ['PEN (BLUE/RED/BLACK) DOZEN', 'dozen', 5000],
 ['PEN NATARAJ (BLUE/BLACK) PIECE', 'piece', 500],
 ['PEN NATARAJ (BLUE/BLACK) DOZEN', 'dozen', 1500],
 ['BAITASHA A6 PIECE', 'piece', 100],
 ['BAITASHA A6 DOZEN', 'dozen', 2500],
 ['BAITASHA A3 PIECE', 'piece', 500],
 ['BAITASHA A3 DOZEN', 'dozen', 7000],
 ['BAITASHA A4 PIECE', 'piece', 200],
 ['BAITASHA A4 DOZEN', 'dozen', 5000],
 ['DAFTARI PAGE 100 PIECE', 'piece', 1000],
 ['DAFTARI PAGE 100 DOZEN', 'dozen', 8000],
 ['DAFTARI PAGE 200 PIECE', 'piece', 1300],
 ['DAFTARI PAGE 200 DOZEN', 'dozen', 12000],
 ['DAFTARI STIFF COVER PIECE', 'piece', 1500],
 ['DAFTARI STIFF COVER DOZEN', 'dozen', 14000],
 ['DAFTARI COUNTER BOOK Q2 PIECE', 'piece', 2000],
 ['DAFTARI COUNTER BOOK Q2 DOZEN', 'dozen', 20000],
 ['DAFTARI COUNTER BOOK Q3 PIECE', 'piece', 2500],
 ['DAFTARI COUNTER BOOK Q3 DOZEN', 'dozen', 25000],
 ['DAFTARI MSOMI PIECE', 'piece', 800],
 ['DAFTARI MSOMI DOZEN', 'dozen', 8000],
 ['SPRAY ALL COLORS PIECE', 'piece', 3000],
 ['PHOTO PAPER PASSPORT 4R-A6 DOZEN', 'dozen', 5000],
 ['PHOTO PAPER 4R-A5 DOZEN', 'dozen', 6000],
 ['PHOTO PAPER STICKER A4 DOZEN', 'dozen', 9000],
 ['PHOTO PAPER GLOSS A4 DOZEN', 'dozen', 9000],
 ['PHOTO PAPER GLOSS A3 DOZEN', 'dozen', 18000],
 ['PHOTO PAPER STICKER A3 DOZEN', 'dozen', 18000],
 ['SPIRAL FILE PIECE', 'piece', 1500],
 ['SPIRAL FILE DOZEN', 'dozen', 12000],
 ['FILE NDOGO PIECE', 'piece', 1000],
 ['FILE NDOGO DOZEN', 'dozen', 8000],
 ['FILE KUBWA PIECE', 'piece', 3000],
 ['FILE KUBWA DOZEN', 'dozen', 30000],
 ['GLUE STICK SIZE KATI PIECE', 'piece', 1000],
 ['GLUE STICK SIZE KATI DOZEN', 'dozen', 12000],
 ['GLUE OFFICE PIECE', 'piece', 1000],
 ['GLUE OFFICE DOZEN', 'dozen', 8500],
 ['MASKING TAPE PIECE', 'piece', 1000],
 ['MASKING TAPE DOZEN', 'dozen', 8000],
 ['TAPE KUBWA PIECE', 'piece', 5000],
 ['TAPE SIZE KATI PIECE', 'piece', 4000],
 ['TAPE SIZE MEDIUM PIECE', 'piece', 1000],
 ['TAPE SIZE NDOGO PIECE', 'piece', 500],
 ['GUN HEAT NDOGO PIECE', 'piece', 500],
 ['GRAPH PAD PIECE', 'piece', 100],
 ['GRAPH PAD DOZEN', 'dozen', 2500],
 ['RULER WHITE PIECE', 'piece', 500],
 ['RULER WHITE DOZEN', 'dozen', 2500],
 ['RULER DOMS PIECE', 'piece', 1000],
 ['RULER DOMS DOZEN', 'dozen', 8000],
 ['MATHEMATICAL SET OXFORD PIECE', 'piece', 2500],
 ['MATHEMATICAL SET OXFORD DOZEN', 'dozen', 24000],
 ['MATHEMATICAL SET DOMS PIECE', 'piece', 5000],
 ['MATHEMATICAL SET NATARAJ PIECE', 'piece', 6000],
 ['DIARY A6 PIECE', 'piece', 5000],
 ['DIARY A5 PIECE', 'piece', 6000],
 ['DIARY A4 PIECE', 'piece', 7000],
 ['UFUTIO PIECE', 'piece', 300],
 ['KICHONGEO PIECE', 'piece', 300],
 ['STAPE PIN DOZEN', 'dozen', 1500],
 ['CORRECTION FLUID PIECE', 'piece', 1000],
 ['CORRECTION FLUID DOZEN', 'dozen', 9000],
 ['COLOR PENCIL PIECE', 'piece', 1000],
 ['WATER COLOR PIECE', 'piece', 5000],
 ['KNIFE MODE NDOGO PIECE', 'piece', 800],
 ['KNIFE MODE KUBWA PIECE', 'piece', 1000],
 ['MIKASI MIDOGO PIECE', 'piece', 1500],
 ['MIKASI MIKUBWA PIECE', 'piece', 2000],
 ['ID HOLDER KAWAIDA PIECE', 'piece', 1000],
 ['ID HOLDER DOUBLE SIDE PIECE', 'piece', 2000],
 ['LAMINATION FILM DOZEN', 'dozen', 16000],
 ['STICK NOTE PIECE', 'piece', 1000],
 ['STICK NOTE DOZEN', 'dozen', 8000],
 ['RULED PAPER DOZEN', 'dozen', 11000],
 ['RULED PAPER PIECE', 'piece', 50],
 ['SHORTHAND DOZEN', 'dozen', 9000],
 ['SHORTHAND PIECE', 'piece', 1000],
 ['MARK PEN DOZEN', 'dozen', 2500],
 ['MARK PEN PIECE', 'piece', 500],
 ['HIGHLIGHTER PIECE', 'piece', 1000],
 ['HIGHLIGHTER DOZEN', 'dozen', 8000],
];

const rows = db.prepare("SELECT name, unit, selling_price FROM products WHERE status = 'active'").all();
const dbMap = new Map(rows.map((r) => [r.name, r]));
let ok = 0;
const problems = [];
for (const [name, unit, price] of EXPECTED) {
 const r = dbMap.get(name);
 if (!r) { problems.push(`MISSING: ${name}`); continue; }
 if (Number(r.selling_price) !== price || r.unit !== unit) {
  problems.push(`MISMATCH: ${name} — db: ${r.selling_price}/${r.unit}, expected: ${price}/${unit}`);
 } else ok++;
}
const extra = rows.filter((r) => !EXPECTED.find((e) => e[0] === r.name));
console.log(`checked ${EXPECTED.length} items | exact match: ${ok} | problems: ${problems.length + extra.length}`);
for (const p of problems) console.log(p);
for (const e of extra) console.log(`EXTRA ACTIVE PRODUCT NOT IN LIST: ${e.name} (${e.selling_price})`);
